### ISSUE TITLE
1.- Yo como usuario nuevo quiero poder crear una cuenta con email y password válidos para poder iniciar sesión e ingresar a la red social.

### ISSUE THREAD

**Issue by Karen753** [MariangelMoraMarquez/LIM011-fe-social-network#1]
CRITERIOS DE ACEPTACIÓN
- [x] Si hay un error validando el nuevo usuario debe ser visible
- [x] Debe ser responsive
- [x] No debe recargar la pagina para crear la cuenta.

DEFINCIÓN DE TERMINADO

- [x] Cumple con los criterios de aceptación.
- [x] Debe pasar los test unitarios
- [x] El diseño visual corresponde al prototipo (FIGMA)
- [x] Se realizo las pruebas de usabilidad y se implementó feedback

**Comment by Karen753** [comment]
hola

**Comment by MariangelMM** [comment]
historia terminada
